# docs.world.ac Jekyll Config File.
# Careful messing with this if you don't know what it means! Find out more at jekyllrb.com
# Last Major Release: 1.0.0

# General Site Build Settings
title: World Affairs Conference Documentation
description: The World Affairs Conference Documentation Website!
baseurl: ""
url: "docs.world.ac"
github: "https://github.com/worldaffairsconference/docs/"

# Build settings
markdown: kramdown

# Rendered Collections
collections:
  frontend:
    output: true
    layout: frontend
  backend:
    output: true
    layout: backend

# Excludes
exclude:
  - vendor/bundle
  - ".travis.yml"
  - README.md
  - "*.sh"
  - Gemfile
  - Gemfile.lock
  - Rakefile
